Campeonato = ('Sporting','Porto','Benfica','Braga','Guimarães','Boavista','Gil Vicente','B-SAD','Santa Clara','Marítimo','Portimonense','Famalicão','Estoril','Tondela','Vizela','Moreirense','Paços Ferreira','Arouca')
print('*'*60)
print(Campeonato)
print('*'*60)
print(Campeonato[:5])
print('*'*60)
print(Campeonato[-4:])
print('*'*60)
print(sorted(Campeonato))
print('*'*60)
print(f"O {Campeonato[5]} está na {Campeonato.index('Boavista')+1}ª posição")